# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tweety/cpp-course/tower-defense

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tweety/cpp-course/tower-defense

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tweety/cpp-course/tower-defense/CMakeFiles /home/tweety/cpp-course/tower-defense//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tweety/cpp-course/tower-defense/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named YourExecutable

# Build rule for target.
YourExecutable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 YourExecutable
.PHONY : YourExecutable

# fast build rule for target.
YourExecutable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/build
.PHONY : YourExecutable/fast

src/bombProjectile.o: src/bombProjectile.cpp.o
.PHONY : src/bombProjectile.o

# target to build an object file
src/bombProjectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bombProjectile.cpp.o
.PHONY : src/bombProjectile.cpp.o

src/bombProjectile.i: src/bombProjectile.cpp.i
.PHONY : src/bombProjectile.i

# target to preprocess a source file
src/bombProjectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bombProjectile.cpp.i
.PHONY : src/bombProjectile.cpp.i

src/bombProjectile.s: src/bombProjectile.cpp.s
.PHONY : src/bombProjectile.s

# target to generate assembly for a file
src/bombProjectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bombProjectile.cpp.s
.PHONY : src/bombProjectile.cpp.s

src/bombTower.o: src/bombTower.cpp.o
.PHONY : src/bombTower.o

# target to build an object file
src/bombTower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bombTower.cpp.o
.PHONY : src/bombTower.cpp.o

src/bombTower.i: src/bombTower.cpp.i
.PHONY : src/bombTower.i

# target to preprocess a source file
src/bombTower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bombTower.cpp.i
.PHONY : src/bombTower.cpp.i

src/bombTower.s: src/bombTower.cpp.s
.PHONY : src/bombTower.s

# target to generate assembly for a file
src/bombTower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bombTower.cpp.s
.PHONY : src/bombTower.cpp.s

src/bulletProjectile.o: src/bulletProjectile.cpp.o
.PHONY : src/bulletProjectile.o

# target to build an object file
src/bulletProjectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bulletProjectile.cpp.o
.PHONY : src/bulletProjectile.cpp.o

src/bulletProjectile.i: src/bulletProjectile.cpp.i
.PHONY : src/bulletProjectile.i

# target to preprocess a source file
src/bulletProjectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bulletProjectile.cpp.i
.PHONY : src/bulletProjectile.cpp.i

src/bulletProjectile.s: src/bulletProjectile.cpp.s
.PHONY : src/bulletProjectile.s

# target to generate assembly for a file
src/bulletProjectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bulletProjectile.cpp.s
.PHONY : src/bulletProjectile.cpp.s

src/bulletTower.o: src/bulletTower.cpp.o
.PHONY : src/bulletTower.o

# target to build an object file
src/bulletTower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bulletTower.cpp.o
.PHONY : src/bulletTower.cpp.o

src/bulletTower.i: src/bulletTower.cpp.i
.PHONY : src/bulletTower.i

# target to preprocess a source file
src/bulletTower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bulletTower.cpp.i
.PHONY : src/bulletTower.cpp.i

src/bulletTower.s: src/bulletTower.cpp.s
.PHONY : src/bulletTower.s

# target to generate assembly for a file
src/bulletTower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/bulletTower.cpp.s
.PHONY : src/bulletTower.cpp.s

src/enemy.o: src/enemy.cpp.o
.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i
.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s
.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map.o: src/map.cpp.o
.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/path.o: src/path.cpp.o
.PHONY : src/path.o

# target to build an object file
src/path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/path.cpp.o
.PHONY : src/path.cpp.o

src/path.i: src/path.cpp.i
.PHONY : src/path.i

# target to preprocess a source file
src/path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/path.cpp.i
.PHONY : src/path.cpp.i

src/path.s: src/path.cpp.s
.PHONY : src/path.s

# target to generate assembly for a file
src/path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/path.cpp.s
.PHONY : src/path.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/projectile.o: src/projectile.cpp.o
.PHONY : src/projectile.o

# target to build an object file
src/projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/projectile.cpp.o
.PHONY : src/projectile.cpp.o

src/projectile.i: src/projectile.cpp.i
.PHONY : src/projectile.i

# target to preprocess a source file
src/projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/projectile.cpp.i
.PHONY : src/projectile.cpp.i

src/projectile.s: src/projectile.cpp.s
.PHONY : src/projectile.s

# target to generate assembly for a file
src/projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/projectile.cpp.s
.PHONY : src/projectile.cpp.s

src/tower.o: src/tower.cpp.o
.PHONY : src/tower.o

# target to build an object file
src/tower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/tower.cpp.o
.PHONY : src/tower.cpp.o

src/tower.i: src/tower.cpp.i
.PHONY : src/tower.i

# target to preprocess a source file
src/tower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/tower.cpp.i
.PHONY : src/tower.cpp.i

src/tower.s: src/tower.cpp.s
.PHONY : src/tower.s

# target to generate assembly for a file
src/tower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/YourExecutable.dir/build.make CMakeFiles/YourExecutable.dir/src/tower.cpp.s
.PHONY : src/tower.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... YourExecutable"
	@echo "... src/bombProjectile.o"
	@echo "... src/bombProjectile.i"
	@echo "... src/bombProjectile.s"
	@echo "... src/bombTower.o"
	@echo "... src/bombTower.i"
	@echo "... src/bombTower.s"
	@echo "... src/bulletProjectile.o"
	@echo "... src/bulletProjectile.i"
	@echo "... src/bulletProjectile.s"
	@echo "... src/bulletTower.o"
	@echo "... src/bulletTower.i"
	@echo "... src/bulletTower.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/path.o"
	@echo "... src/path.i"
	@echo "... src/path.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/projectile.o"
	@echo "... src/projectile.i"
	@echo "... src/projectile.s"
	@echo "... src/tower.o"
	@echo "... src/tower.i"
	@echo "... src/tower.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

